[package]
name = "unicola_codegen"
version = "0.0.0"
authors = ["Chiu-Hsiang Hsu <wdv4758h@gmail.com>"]

[dependencies]
phf_codegen = "0.7.18"
csv = { version = "0.14.7", optional = true }

[features]
default = ["eac"]
eac = ["csv"]
